version: "3.9"
services:
  web:
    build:
      context: .
    image: pr-lab1-httpfs:latest
    container_name: pr-lab1-web
    ports:
      - "8081:8080"

   
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/').read()"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s

    restart: unless-stopped
